#!/bin/bash
if rpm -q scratch &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Scratch is already installed."
else 
	enable-repo unsupported
	pkexec dnf install --assumeyes scratch
	if rpm -q scratch &>/dev/null; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Scratch successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Scratch not installed."
	fi
fi
