#!/bin/bash
if rpm -q stellarium &>/dev/null; then
	kdialog --title $"OpenMandriva"  --msgbox  $" Stellarium is already installed."
else 
	enable-repo unsupported
	pkexec dnf install --assumeyes stellarium
	if rpm -q stellarium &>/dev/null; then
		kdialog --title $"OpenMandriva"  --msgbox  $" Stellarium successfully installed."
	else
		kdialog --title $"OpenMandriva"  --msgbox  $" Stellarium not installed."
	fi
fi
